### PR TITLE
Add deprecated attribute

### PR DESCRIPTION
**Pull request by 0xc0170**
Tested with armcc, gcc. 

A note: I looked at IAR, they don't support any pragma with similar functionality :disappointed: 

@autopulated @bogdanm

### CODE REVIEW

**Comment by bogdanm** [comment]
+1

**Comment by autopulated** [comment]
Live in 1.1.0. Note that we should be using "^1.1.0" as the dependency spec when depending on this module, as it is >=1.x.x :)

**Comment by bogdanm** [comment]
Is there a good reason why we should use the node-semver notation instead of the more explicit '>=, <=' ?

**Comment by autopulated** [comment]
I'm struggling to articulate one other than "brevity", but yes I think there is... I think if you have two numbers to update you're more likely to make a mistake?

**Comment by bogdanm** [comment]
Good point. To me, `>=, <=` and other such combinations are easier to read and understand (I needed to lookup up the definition of `^` **again** after your comment), but all in all, I understand why this style has its advantages.

**Pull request merged**
